### ISSUE TITLE
Adding a data generator

### ISSUE THREAD

**Issue by jhuus** [sayakpaul/Sharpness-Aware-Minimization-TensorFlow#2]
That's a great example - thanks. When I try replacing train_ds with a data generator though, I get "NotImplementedError: When subclassing the `Model` class, you should implement a `call` method." I also tried adding this call method to SAMModel, but that didn't work either:

    def call(self, inputs):
        return self.resnet_model(inputs)

Any ideas? The attached main.py runs your code plus a simple data generator which just shuffles the training data.

[main.zip](https://github.com/sayakpaul/Sharpness-Aware-Minimization-TensorFlow/files/6176130/main.zip)

**Comment by sayakpaul** [comment]
Unfortunately I don't have the bandwidth to look into your code. 

If your generator yields the features and the labels, then it need to be handled like:

```
def call(self, inputs):
    x, _ = inputs
    return self.your_model(x)
```

I would recommend using tf.data for creating your data generators because of performance reasons. I am also shuffling the dataset while building the pipeline if that's a concern.

**Comment by jhuus** [comment]
Thanks for the quick reply and feedback. I'll look into implementing my
generator logic using tf.data.

**Comment by jhuus** [comment]
I now have it working, except that model.save doesn't work. I tried a few
things but was unable to make that work. If you're able to add that to your
example sometime, that would be great.

Best regards,

Jan Huus

**Comment by sayakpaul** [comment]
I am not sure how you are saving the model. Please keep in mind that `SAMModel` class is just an encapsulation of the training logic of SAM. So traditional `save` and `save_weights()` functions won't work as expected here. We are rather interested in serialzing the model (specifically `SAMModel(). resnet_model`) we are training via the wrapper class. 

So, if the `SAMModel` class is initialized as - `model = SAMModel(utils.get_training_model())` you would serialize the `resnet_model` that is present inside `model`. In code it would be - `model.resnet_model.save("your_saved_model_folder")`.

**Comment by jhuus** [comment]
Of course - that makes sense. Thanks again.

Jan
