### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by lucasliunju** [sayakpaul/Sharpness-Aware-Minimization-TensorFlow#3]
Hi, Sayak

Thanks for your contribution. I have a question about why the the model with SAM is not better than the model without SAM. Tnank you!

Yong

**Comment by sayakpaul** [comment]
Refer here: https://github.com/sayakpaul/Sharpness-Aware-Minimization-TensorFlow/issues/1.

**Comment by lucasliunju** [comment]
Hi Sayak,

That's a wonderful work. Thanks for your contribution. I would like to ask whether we can have an communication about this paper.

Thank you!

Yong

**Comment by sayakpaul** [comment]
Feel free to.
